# Generated by Django 4.2.16 on 2024-10-22 01:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='sieve_api.message')),
            ],
        ),
        migrations.CreateModel(
            name='ChatCompletionResponseDb',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object', models.CharField(max_length=255)),
                ('created', models.DateTimeField()),
                ('model', models.CharField(max_length=255)),
                ('choices', models.ManyToManyField(related_name='chat_completions', to='sieve_api.choice')),
            ],
        ),
    ]
