# Generated by Django 4.2.16 on 2024-10-22 03:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sieve_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveChat',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('eca66f28-7e5f-4088-8713-838ac5fa5dbf'), editable=False, primary_key=True, serialize=False)),
                ('object', models.CharField(max_length=255)),
                ('created', models.DateTimeField()),
                ('model', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='message',
        ),
        migrations.AddField(
            model_name='choice',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='choice',
            name='fullname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='choice',
            name='role',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='choice',
            name='id',
            field=models.UUIDField(default=uuid.UUID('639311d7-b13e-467c-ac94-009707156cc8'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='choice',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ChatCompletionResponseDb',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.AddField(
            model_name='choice',
            name='chat_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='sieve_api.activechat'),
        ),
    ]
