# Generated by Django 4.2.16 on 2024-10-22 21:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sieve_api', '0002_activechat_remove_choice_message_choice_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activechat',
            name='feedback',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='choice',
            name='audio',
            field=models.FileField(default=None, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='activechat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1eb42752-34c1-42ac-9d67-3b7ba828d279'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='choice',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9235ac09-b5db-4d3b-a986-bc65d5c3f913'), editable=False, primary_key=True, serialize=False),
        ),
    ]
