# Generated by Django 4.2.16 on 2024-10-23 02:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sieve_api', '0004_activechat_fullname_alter_activechat_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activechat',
            old_name='fullname',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='activechat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ab76b36e-34bb-416f-a386-28fff16e7538'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='choice',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b955447c-a223-4859-b26a-ba96a84ecc5d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
